### ISSUE TITLE
Nginx virtual host

### ISSUE THREAD

**Issue by mat-l** [kanboard/kanboard#182]
Hey,

I am trying to run kanboard via nginx, but it ends up with an error 500.
I added the root path to kanboard to the openbasedir, owned it by the nginx webserver, clone the project from github and sqlite ist enabled in php.ini

Can your help me with the vhost config of the nginx webserver?
        server {
                listen 80;
                server_name kanboard.tdl.com;
                root /srv/http/kanboard;

```
            access_log /.../access.log;
            error_log /.../error.log;

            index index.php;

    location ~ .php$ {
     fastcgi_pass 127.0.0.1:9000;
     fastcgi_index index.php;
     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
     fastcgi_param PATH_INFO $fastcgi_script_name;
     include /etc/nginx/fastcgi_params;
     }
    }
```

The nginx error logs shows:

```
    2014/07/18 15:34:28 [error] 17593#0: *11 FastCGI sent in stderr: "PHP message: PHP
    Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver'
    in /srv/kanboard/vendor/PicoDb/Drivers/Sqlite.php:20

    Stack trace:
    #0 /srv/http/kanboard/vendor/PicoDb/Drivers/Sqlite.php(20): 
    PDO->__construct('sqlite:data/db....')
    #1 /srv/http/kanboard/vendor/PicoDb/Database.php(22): PicoDb\Sqlite->__construct(Array)
    #2 /srv/http/kanboard/app/common.php(111): PicoDb\Database->__construct(Array)
    #3 /srv/http/kanboard/app/Core/Registry.php(57): {closure}()
    #4 /srv/http/kanboard/app/Core/Registry.php(77): Core\Registry->__get('db')
    #5 /srv/http/kanboard/app/Controller/Base.php(95): Core\Registry->shared('db')
    #6 /srv/http/kanboard/app/Controller/Base.php(117): Controller\Base->__get('config')
    #7 /srv/http/kanboard/app/Core/Router.php(89): Controller\Base->beforeAction('app', 'index')
    #8 /srv/http/kanboard/app/Core/Router.php(109): Core\Router->load('/srv/http/kanbo...',
    '\\Controller\\app', 'index')
    #9 /srv/http/kanboard/index.php(9): Core\Router->execute()
    #10 {main}" while reading response header from upstream, client: xx.xx.xx.xx, server:         
    kanboard.tld.com, request: "GET / HTTP/1.1", upstream:
```

regards mat-l

**Comment by robmoggach** [comment]
Make sure to check your permissions on `/var/lib/php/session/` If the owner is `apache` and your running as `nginx` it won't actually create a session. I almost got caught on this.
