### ISSUE TITLE
Bug with c# stacktrace in task description

### ISSUE THREAD

**Issue by kefran** [kanboard/kanboard#2860]
### Expected behaviour

Tell us what should happen
I create a new task on a project. I copy past an error log with a c# Exception stacktrace as the task description and save it.
I clic on the task on the dashboard to see it.

### Actual behaviour

Tell us what happens instead
I create a new task on a project. I copy past an error log with a c# Exception stacktrace as the task description and save it.
I clic on the task on the dashboard to see it and it failed

HTTP Status : " (failed)net::ERR_CONNECTION_RESET "

### Steps to reproduce

1. Create a new task with a random name
2. past the text bellow in the description field without any formating

```
[2.0.4][bernardx][29/11/2016 11:34:38]
[Message : The process cannot access the file 'H:\PROJETS\EDISON\Tracabilité\Fiche Traçabilité EPDR EDISON 291116.xls' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at DVP_PVP.ViewModel.StandardTestTabStep2ViewModel.UploadTraceability() in D:\schneidf\Visual Studio\Projects\DVP_PVP\ViewModel\StandardTestTabStep2ViewModel.cs:line 256
   at DVP_PVP.FrameworkMvvm.RelayCommand.Execute(Object parameter) in D:\schneidf\Visual Studio\Projects\DVP_PVP\FrameworkMvvm\RelayCommand.cs:line 52
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at DVP_PVP.App.Application_Startup(Object sender, StartupEventArgs e) in D:\schneidf\Visual Studio\Projects\DVP_PVP\App.xaml.cs:line 115]
```

### Configuration

Copy and paste the configuration section from the Kanboard settings page or fill these fields:

- Kanboard version: v1.0.34 
- Database type and version: MySQL 5.6.16
- PHP version: 5.5.6
- OS: Windows Server 2008 R2
- Browser: Chrome Version 54.0.2840.99 m

**Comment by dereks** [comment]
I just tried to reproduce it with today's 'stable' branch.

I was not able to reproduce. It was probably a network issue and not related to your C# stack trace.

**Comment by fguillot** [comment]
I don't really believe the problem is coming from the C# stacktrace. You should provide more details, server logs etc..., there is too little information to be able to troubleshoot something...
