### ISSUE TITLE
JsonRPC createTask problem

### ISSUE THREAD

**Issue by oazabir** [kanboard/kanboard#359]
updateTask works, but createTask fails. I get this error:

```
PHP Fatal error:  Uncaught exception 'BadFunctionCallException' with message 'Bad Request' in /var/www/html/JsonRPC/Client.php:138
Stack trace:
#0 /var/www/html/JsonRPC/Client.php(93): JsonRPC\Client->execute('createTask', Array)
#1 /var/www/html/taskforasg.php(49): JsonRPC\Client->__call('createTask', Array)
#2 /var/www/html/taskforasg.php(49): JsonRPC\Client->createTask(Array)
#3 {main}
  thrown in /var/www/html/JsonRPC/Client.php on line 138

Fatal error: Uncaught exception 'BadFunctionCallException' with message 'Bad Request' in /var/www/html/JsonRPC/Client.php:138
Stack trace:
#0 /var/www/html/JsonRPC/Client.php(93): JsonRPC\Client->execute('createTask', Array)
#1 /var/www/html/taskforasg.php(49): JsonRPC\Client->__call('createTask', Array)
#2 /var/www/html/taskforasg.php(49): JsonRPC\Client->createTask(Array)
#3 {main}
  thrown in /var/www/html/JsonRPC/Client.php on line 138
```

Here's my code:

```
$task = array(
            'title' => $taskTitle,
            'color_id' => 'blue',
            'owner_id' => $user_id,
            'project_id' => $project_id,
            'column_id' => 1
        );
print_r($task);
$result = $client->createTask($task);
echo 'Result:'.$result;
```

If I change createTask to updateTask and pass an id, then it works. But createTask throws the exception.

**Comment by nipasoni** [comment]
how we can assign column id in create task
