### ISSUE TITLE
How a plugin can execute code periodically ?

### ISSUE THREAD

**Issue by jajm** [kanboard/kanboard#3656]
I'm trying to execute code each time the cronjob is run, but I can't do it.
What I tried:

### With `\Kanboard\Core\Plugin\Base::on`
In Plugin.php:
```php
public function initialize()
{
    $this->on(TaskModel::EVENT_DAILY_CRONJOB, function () {});
}
```

When I run ./cli cronjob, this fails with the following message:

```
PHP Fatal error:  Uncaught Error: Cannot use object of type Closure as array in /home/kanboard/kanboard/app/Console/TaskTriggerCommand.php:38
Stack trace:
#0 /home/kanboard/kanboard/app/Console/TaskTriggerCommand.php(21): Kanboard\Console\TaskTriggerCommand->getProjectIds()
#1 /home/kanboard/kanboard/vendor/symfony/console/Command/Command.php(259): Kanboard\Console\TaskTriggerCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#2 /home/kanboard/kanboard/app/Console/CronjobCommand.php(29): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#3 /home/kanboard/kanboard/vendor/symfony/console/Command/Command.php(259): Kanboard\Console\CronjobCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/kanboard/kanboard/vendor/symfony/console/Application.php(844): Symfony\Component\Console\Comm in /home/kanboard/kanboard/app/Console/TaskTriggerCommand.php on line 38
```

### With an event subscriber

```php
class MySubscriber implements \Symfony\Component\EventDispatcher\EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return array(
            TaskModel::EVENT_DAILY_CRONJOB => 'dailyCronjob',
        );
    }

    public function dailyCronjob() {}
}
```

It fails with the following error

```
PHP Fatal error:  Uncaught Error: Call to undefined method Kanboard\Plugin\MyPlugin\Subscriber\MySubscriber::getProjectId() in /home/kanboard/kanboard/app/Console/TaskTriggerCommand.php:38
Stack trace:
#0 /home/kanboard/kanboard/app/Console/TaskTriggerCommand.php(21): Kanboard\Console\TaskTriggerCommand->getProjectIds()
#1 /home/kanboard/kanboard/vendor/symfony/console/Command/Command.php(259): Kanboard\Console\TaskTriggerCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#2 /home/kanboard/kanboard/app/Console/CronjobCommand.php(29): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\NullOutput))
#3 /home/kanboard/kanboard/vendor/symfony/console/Command/Command.php(259): Kanboard\Console\CronjobCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/kanboard/kanboard/vendor/symfony/console/App in /home/kanboard/kanboard/app/Console/TaskTriggerCommand.php on line 38
```

It appears to only work with `Action`s, is it intended ?
I could implement the corresponding Action but that means I would have to setup
an automatic action for every project, and I would like to avoid that.

Is there another way to execute code periodically ?

### Configuration

- Kanboard version: 1.1.1
- PHP version: 7.0.19

**Comment by bugwatcher** [comment]
This issue has been closed automatically by a bot because it was tagged as **"question"**. Please, use the [forum](https://github.com/kanboard/forum/issues) for open discussions to avoid polluting the bug tracker. Thank you for your understanding.
