### ISSUE TITLE
Fatal error with PicoDb, SQL Exception

### ISSUE THREAD

**Issue by AurelienC** [kanboard/kanboard#3762]
Hello,

Since this afternoon, I have an error with my Kanboard. I have just make read with API, but no modifications.

Any idea ?

Thanks !

`Fatal error: Uncaught PicoDb\SQLException: SQL error in /home/fr/www/board/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:351 Stack trace: #0 /home/fr/www/board/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\StatementHandler->handleSqlError(Object(PDOException)) #1 /home/fr/www/board/vendor/fguillot/picodb/lib/PicoDb/Table.php(237): PicoDb\StatementHandler->execute() #2 /home/fr/www/board/app/Core/Session/SessionHandler.php(67): PicoDb\Table->insert(Array) #3 [internal function]: Kanboard\Core\Session\SessionHandler->write('8eczv2t8RcHrcor...', 'csrf|a:1:{s:60:...') #4 [internal function]: session_write_close() #5 {main} thrown in /home/fr/www/board/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 351`

**Comment by AurelienC** [comment]
I have downloaded db.sqlite and make `VACUUM;` with https://sqliteonline.com/ and re-upload the new db.sql.

It's OK !
