### ISSUE TITLE
PHP error when fishing subtask in zero seconds

### ISSUE THREAD

**Issue by arjanverduijn** [kanboard/kanboard#3894]
### Actual behaviour

When checking multiple subtask (in zero time, by double clicking them) the server responds with a HTTP 500 error.

### Expected behaviour

I would to be able to finalize subtasks without having to use the time tracking feature.

### Steps to reproduce

Take any task with multiple subtasks, double click the first and click any other subtask.

### Log

PHP error message:
PHP Fatal error: Uncaught TypeError: Argument 2 passed to Kanboard\Helper\FormHelper::hidden() must be of the type array, null given, called in C:\inetpub\wwwroot\kanboard\app\Template\subtask_restriction\show.php on line 10 and defined in C:\inetpub\wwwroot\kanboard\app\Helper\FormHelper.php:34 Stack trace: #0 C:\inetpub\wwwroot\kanboard\app\Template\subtask_restriction\show.php(10): Kanboard\Helper\FormHelper->hidden('id', NULL) #1 C:\inetpub\wwwroot\kanboard\app\Core\Template.php(83): include('C:\\inetpub\\wwwr...') #2 C:\inetpub\wwwroot\kanboard\app\Controller\SubtaskRestrictionController.php(32): Kanboard\Core\Template->render('subtask_restric...', Array) #3 C:\inetpub\wwwroot\kanboard\app\Core\Controller\Runner.php(77): Kanboard\Controller\SubtaskRestrictionController->show() #4 C:\inetpub\wwwroot\kanboard\app\Core\Controller\Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #5 C:\inetpub\wwwroot\kanboard\index.php(9): Kanboard\Core\Controller\Runner->execute() #6 {main} thrown in C:\inetpub\wwwroot\kanboard\app\Helper\FormHelper.php on line 34 

### Configuration

- Kanboard version: 1.2.2
- Database type and version: MySQL, 5.7.16-log
- PHP version: 7.1.11
- OS: Windows 7
- Browser: MS IE

**Comment by arjanverduijn** [comment]
I seem to be the only one experiencing this kind of problem. In view of not polluting the list with indefinitly open issues, I am closing this one.
