### ISSUE TITLE
ERROR UPGRADE 1.2.4 - 1.2.5 Internal Server Error

### ISSUE THREAD

**Issue by mekabyte** [kanboard/kanboard#3926]
This issue is: I followed the instructions to the letter and did not manage to access the admin screen after updating

- [ x] Bug report
- [ ] Feature request
- [ ] Improvement

- Please, read the [Frequently Asked Questions](https://docs.kanboard.org/en/latest/developer_guide/faq.html).
- Ask questions on the [Forum](https://github.com/kanboard/forum/issues).
- hecho  /done

### Actual behaviour
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@misoporte.com.ar to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
Apache/2.4.33 (cPanel) OpenSSL/1.0.2o mod_bwlimited/1.4 Server at www.misoporte.com.ar Port 80

### Expected behaviour
UPGRADE TO V 1.2.5

### Steps to reproduce

    Decompress the new archive 
-done
    Copy the data folder into the newly uncompressed directory
-done
    Copy your custom config.php if you have one
-done
    If you have installed some plugins, use the latest version
-done
    Make sure the directory data is writeable by your web server user
-done
    Modify .htaccess if needed (f.e. forcing SSL)
- no need
    Test
- wrong
    Remove your old Kanboard directory
-NO YET 

### Logs
[21-May-2018 15:46:22 UTC] PHP Fatal error:  Uncaught exception 'PicoDb\SQLException' with message 'SQL Error: SQLSTATE[HY000]: General error: 1 no such table: sessions' in /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:351
Stack trace:
#0 /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\StatementHandler->handleSqlError(Object(PDOException))
#1 /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php(257): PicoDb\StatementHandler->execute()
#2 /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Table.php(363): PicoDb\Database->execute('SELECT 1 FROM "...', Array)
#3 /home/misoporte/public_html/kanboard/app/Core/Session/SessionHandler.php(59): PicoDb\Table->exists()
#4 [internal function]: Kanboard\Core\Session\SessionHandler->write('9EzGZg2,fFsyhPQ...', '')
#5 [internal function]: session_write_close()
#6 {main}
  thrown in /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 351
[21-May-2018 14:07:36 America/Argentina/Ushuaia] Kanboard: user eduardo authentication failure
[21-May-2018 14:07:54 America/Argentina/Ushuaia] Kanboard: user eduardo@misoporte.com.ar  authentication failure
[21-May-2018 14:10:10 America/Argentina/Ushuaia] Kanboard: user eduardo authentication failure
[21-May-2018 14:21:41 America/Argentina/Ushuaia] Kanboard: user admin authentication failure
[21-May-2018 14:22:27 America/Argentina/Ushuaia] Kanboard: user admin authentication failure
[21-May-2018 14:22:42 America/Argentina/Ushuaia] Kanboard: user admin authentication failure
[21-May-2018 14:23:14 America/Argentina/Ushuaia] Kanboard: user admin authentication failure
[21-May-2018 14:23:40 America/Argentina/Ushuaia] Kanboard: user admin authentication failure
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  stat(): stat failed for /home/misoporte/public_html/kanboard/public_html/kanboard/data in /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php on line 35
[21-May-2018 16:56:08 America/Argentina/Ushuaia] [error] Unable to create folder to store uploaded files, check the permissions of the parent directory (file=/home/misoporte/public_html/kanboard/public_html/kanboard/data; mode=0; uid=0; gid=0)
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 217
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 218
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 16:56:08 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  stat(): stat failed for /home/misoporte/public_html/kanboard/public_html/kanboard/data in /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php on line 35
[21-May-2018 17:02:32 America/Argentina/Ushuaia] [error] Unable to create folder to store uploaded files, check the permissions of the parent directory (file=/home/misoporte/public_html/kanboard/public_html/kanboard/data; mode=0; uid=0; gid=0)
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 217
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 218
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[21-May-2018 17:02:32 America/Argentina/Ushuaia] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/misoporte/public_html/kanboard/app/ServiceProvider/ObjectStorageProvider.php:35) in /home/misoporte/public_html/kanboard/app/Core/Http/Response.php on line 222
[22-May-2018 16:36:15 America/Argentina/Ushuaia] Kanboard: user eduardo@misoporte.com.ar authentication failure
[22-May-2018 16:36:26 America/Argentina/Ushuaia] Kanboard: user eduardo@misoporte.com.ar authentication failure
[22-May-2018 16:36:33 America/Argentina/Ushuaia] Kanboard: user eduardo@misoporte.com.ar authentication failure
[22-May-2018 16:36:44 America/Argentina/Ushuaia] Kanboard: user Administrator authentication failure
[22-May-2018 16:36:53 America/Argentina/Ushuaia] Kanboard: user eduardo@misoporte.com.ar authentication failure
[22-May-2018 21:12:52 America/Argentina/Ushuaia] Kanboard: user admin authentication failure

[13-Jun-2018 15:11:14 UTC] PHP Warning:  Error while sending QUERY packet. PID=2992 in /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240
[13-Jun-2018 15:11:18 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:240) in /home/misoporte/public_html/kanboard/app/Core/Session/SessionManager.php on line 50
[13-Jun-2018 15:11:31 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:12:29 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:13:29 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:14:29 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:15:29 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:16:29 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:17:29 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:18:33 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:32:53 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:32:53 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:34:59 UTC] [error] Bigboard is not compatible with this version
[13-Jun-2018 15:36:35 UTC] PHP Warning:  Error while sending QUERY packet. PID=4691 in /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240
[13-Jun-2018 15:36:39 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:240) in /home/misoporte/public_html/kanboard/app/Core/Session/SessionManager.php on line 50
[13-Jun-2018 15:36:56 UTC] PHP Warning:  Error while sending QUERY packet. PID=5110 in /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240
[13-Jun-2018 15:36:56 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:240) in /home/misoporte/public_html/kanboard/app/Core/Session/SessionManager.php on line 50
[13-Jun-2018 15:37:08 UTC] PHP Warning:  Error while sending QUERY packet. PID=5067 in /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240
[13-Jun-2018 15:37:08 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/misoporte/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:240) in /home/misoporte/public_html/kanboard/app/Core/Session/SessionManager.php on line 50
[13-Jun-2018 17:32:59 UTC] [error] Bigboard is not compatible with this version

### Configuration

CPANEL 11

    Versión de la aplicación: 1.2.4
    Versión de PHP: 7.0.30
    PHP SAPI: fpm-fcgi
    Versión del sistema operativo: Linux 2.6.32-042stab127.2
    Driver de la base de datos mysql
    Versión de base de datos: 5.5.59-cll
    Navegador: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

Gracias !!!! 
in Advance!!

**Comment by Victor-IT** [comment]
my error after upgrade is:
`Internal Error: SQL Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'points' in 'field list'`

**Comment by MichaelTunnell** [comment]
this error also applies when trying to install a brand new version of Kanboard with version 1.2.5.

**Comment by bugwatcher** [comment]
Please, use the new forum for questions or installation issues: https://kanboard.discourse.group/

**Comment by k00ni** [comment]
Further discussion can be found at: https://kanboard.discourse.group/t/internal-error-unable-to-create-folder-to-store-uploaded-files-check-the-permissions-of-the-parent-directory/19
