### ISSUE TITLE
empty captcha images

### ISSUE THREAD

**Issue by minusf** [kanboard/kanboard#4199]
### Actual behaviour

Captcha image on login page empty

### Expected behaviour

Visible captcha image

### Steps to reproduce

Try to login

### Screenshots

<img width="338" alt="Screenshot 2019-05-24 at 13 51 34" src="https://user-images.githubusercontent.com/3632883/58325756-1014c180-7e2b-11e9-9d52-4bf6524830b6.png">

### Logs

```
[2019-05-24 11:52:50] [debug] Kanboard\Core\Controller\Runner::executeMiddleware                                                                                                   
[2019-05-24 11:52:50] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2019-05-24 13:52:50] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
[2019-05-24 13:52:50] [debug] Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\AuthController::check
[2019-05-24 13:52:50] [debug] SQL: SELECT "data" FROM "sessions"   WHERE "id" = ?    LIMIT 1
[2019-05-24 13:52:50] [debug] SQL: query_duration=0.00089406967163086     
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.00089406967163086
[2019-05-24 13:52:50] [debug] SQL: SELECT "option", "value" FROM "settings"
[2019-05-24 13:52:50] [debug] SQL: query_duration=4.5061111450195E-5      
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.00093913078308105                                                                                                        
[2019-05-24 13:52:50] [debug] SQL: SELECT * FROM "actions"           
[2019-05-24 13:52:50] [debug] SQL: query_duration=4.3869018554688E-5     
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.00098299980163574
[2019-05-24 13:52:50] [debug] SQL: SELECT * FROM "action_has_params"
[2019-05-24 13:52:50] [debug] SQL: query_duration=5.1975250244141E-5
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.0010349750518799     
[2019-05-24 13:52:50] [debug] SQL: SELECT 1 FROM "users"  WHERE "username" = ? AND "lock_expiration_date" != ? AND "lock_expiration_date" >= ?
[2019-05-24 13:52:50] [debug] SQL: query_duration=9.1075897216797E-5            
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.0011260509490967                                                                                                         
[2019-05-24 13:52:50] [debug] SQL: SELECT "nb_failed_login" FROM "users"   WHERE "username" = ?    LIMIT 1                 
[2019-05-24 13:52:50] [debug] SQL: query_duration=3.7908554077148E-5                                                                                                               
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.0011639595031738
[2019-05-24 13:52:50] [debug] SQL: SELECT "nb_failed_login" FROM "users"   WHERE "username" = ?    LIMIT 1
[2019-05-24 13:52:50] [debug] SQL: query_duration=4.4107437133789E-5
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.0012080669403076
[2019-05-24 13:52:50] [debug] SQL: SELECT 1 FROM "sessions"  WHERE "id" = ?
[2019-05-24 13:52:50] [debug] SQL: query_duration=5.0067901611328E-5
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.0012581348419189
[2019-05-24 13:52:50] [debug] SQL: UPDATE "sessions" SET "expire_at"=?, "data"=?  WHERE "id" = ?
[2019-05-24 13:52:50] [debug] SQL: query_duration=0.00027704238891602
[2019-05-24 13:52:50] [debug] SQL: total_execution_time=0.001535177230835
[2019-05-24 13:52:50] [debug] APP: nb_queries=9
[2019-05-24 13:52:50] [debug] APP: rendering_time=0.052164077758789
[2019-05-24 13:52:50] [debug] APP: memory_usage=4.6M
[2019-05-24 13:52:50] [debug] APP: uri=/?controller=AuthController&action=check
[2019-05-24 13:52:50] [debug] ###############################################
[2019-05-24 11:52:50] [debug] Kanboard\Core\Controller\Runner::executeMiddleware
[2019-05-24 11:52:50] [debug] Subscriber executed: Kanboard\Subscriber\BootstrapSubscriber::execute
[2019-05-24 13:52:50] [debug] Kanboard\Core\Controller\BaseMiddleware::next => Kanboard\Middleware\AuthenticationMiddleware
[2019-05-24 13:52:50] [debug] Kanboard\Core\Controller\Runner::executeController => \Kanboard\Controller\CaptchaController::image
```
### Configuration

- Kanboard version: `1.2.9`
- Database type and version: Sqlite
- PHP version: `7.1.23`
- OS: macOS 10.14.5
- Browser: firefox/chrome

i am using the macOS builtin php version.  it has gd enabled:

```
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 9 compatible
PNG Support => enabled
libPNG Version => 1.6.32
WBMP Support => enabled
XBM Support => enabled
```

**Comment by ChangePlaces** [comment]
what does the network show for the image?

**Comment by minusf** [comment]
`200` with `0` length

**Comment by rafacamargo123** [comment]
Ok, I did reproduce this on my OSX 10.14, built in php and httpd and got the following error:

```
<b>Fatal error</b>:  Uncaught Error: Call to undefined function imagettfbbox() in /Library/WebServer/Documents/kanboard/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php:327
Stack trace:
#0 /Library/WebServer/Documents/kanboard/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php(441): Gregwar\Captcha\CaptchaBuilder-&gt;writePhrase(Resource id #267, 'ywifl', '/Library/WebSer...', 150, 40)
#1 /Library/WebServer/Documents/kanboard/app/Controller/CaptchaController.php(25): Gregwar\Captcha\CaptchaBuilder-&gt;build()
#2 /Library/WebServer/Documents/kanboard/app/Core/Controller/Runner.php(77): Kanboard\Controller\CaptchaController-&gt;image()
#3 /Library/WebServer/Documents/kanboard/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner-&gt;executeController()
#4 /Library/WebServer/Documents/kanboard/index.php(9): Kanboard\Core\Controller\Runner-&gt;execute()
#5 {main}
  thrown in <b>/Library/WebServer/Documents/kanboard/vendor/gregwar/captcha/src/Gregwar/Captcha/CaptchaBuilder.php</b> on line <b>327</b><br />
```

Doing a quick search, found this: https://stackoverflow.com/questions/26493762/yosemite-el-capitan-php-gd-mcrypt-installation/26505558#26505558 

and many other questions about this.

I've managed to solve on my OSX by installing php7.3 (`brew install php@7.3`). At the end, it will give you directives on how to change the php on your apache. I did it by changing the file `/etc/apache2/httpd.conf`, commenting out `#LoadModule php7_module libexec/apache2/libphp7.so` and adding `LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so`. The other settings that homebrew had suggested to change already existed (Handler and directoryIndex). Restarted apache `apachectl restart` et voilà, captcha worked.

[About homebrew](https://brew.sh/)

You can also [run kanboard with docker](https://docs.kanboard.org/en/latest/admin_guide/docker.html), so you don't have to install things (except for docker) on your machine.

**Comment by minusf** [comment]
oh not this one again..  thanks for the cluestick.  closing.
