### ISSUE TITLE
Unable to login (username and password is required)

### ISSUE THREAD

**Issue by JPRbrs** [kanboard/kanboard#4932]
### Checklist

- [X] I verified that Kanboard is correctly installed
- [X] I verified that the problem does not come from a plugin
- [X] I verified that the problem is not already reported
- [X] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

When trying to log in, the user and password gets rejected and I get presented with username and password is required in the login screen

### Expected behaviour

I'm able to log in and see my boards

### Steps to reproduce
I'm running Kanboard in a container through docker-compose. Usually when I restart the container I need to delete the docker container, copy a backup of the database, and restart the container to access to my boards. This time it didn't work. I've tried changing back the admin password to the default following the steps of an issue (hashing the default admin pass into the sqlite db) but didn't work 

### Logs
PHP message: PHP Fatal error:  Uncaught PicoDb\SQLException: SQL Error: SQLSTATE[HY000]: General error: 11 database disk image is malformed in /var/www/app/libs/picodb/l
ib/PicoDb/StatementHandler.php:351"
Stack trace:"
#0 /var/www/app/libs/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\StatementHandler->handleSqlError(Object(PDOException))"
#1 /var/www/app/libs/picodb/lib/PicoDb/Table.php(237): PicoDb\StatementHandler->execute()"
#2 /var/www/app/app/Core/Session/SessionHandler.php(68): PicoDb\Table->insert(Array)"
#3 [internal function]: Kanboard\Core\Session\SessionHandler->write('kb5ifsqb2trstbc...', 'hasRememberMe|b...')"
#4 [internal function]: session_write_close()"
#5 {main}"
  thrown in /var/www/app/libs/picodb/lib/PicoDb/StatementHandler.php on line 351"
2021/12/27 23:14:27 [error] 17#17: *29 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PicoDb\SQLException: SQL Error: SQLSTATE[HY000]: General error: 1
1 database disk image is malformed in /var/www/app/libs/picodb/lib/PicoDb/StatementHandler.php:351
Stack trace:
#0 /var/www/app/libs/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\StatementHandler->handleSqlError(Object(PDOException))
#1 /var/www/app/libs/picodb/lib/PicoDb/Table.php(237): PicoDb\StatementHandler->execute()
#2 /var/www/app/app/Core/Session/SessionHandler.php(68): PicoDb\Table->insert(Array)
#3 [internal function]: Kanboard\Core\Session\SessionHandler->write('kb5ifsqb2trstbc...', 'hasRememberMe|b...')
#4 [internal function]: session_write_close()
#5 {main}
  thrown in /var/www/app/libs/picodb/lib/PicoDb/StatementHandler.php on line 351" while reading upstream, client: 172.19.0.3, server: localhost, request: "POST /?control
ler=AuthController&action=check HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "redacted"

### Configuration

- Kanboard version: 1.2.16
- Database type and version: sqlite 
- PHP version:
- / # php --version
PHP 7.3.23 (cli) (built: Oct  1 2020 14:34:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.23, Copyright (c) 1999-2018, by Zend Technologies
- OS: alpine:3.15.0
- Browser: Vivaldi

**Comment by JPRbrs** [comment]
Despite the corrupted database message, I'm query the db with sqlite3
