### ISSUE TITLE
Error output reveals too much information, which is a security vulnerability

### ISSUE THREAD

**Issue by sulisu** [kanboard/kanboard#5033]
### Checklist

- [X] I verified that Kanboard is correctly installed
- [X] I verified that the problem does not come from a plugin
- [X] I verified that the problem is not already reported
- [X] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour
When I do some operation, such as draging task, creating task, and there is a database lock problem, Kanboard through a detailed error infomation about this error at the bottom of page. 

This error output include absolute path of php file on the server

for example:
`Fatal error: Uncaught PicoDb\SQLException: SQL Error: SQLSTATE[HY000]: General error: 5 database is locked in /absolute/path/to/file/on/disk/kanboard/libs/picodb/lib/PicoDb/StatementHandler.php:351 Stack trace: #0 /absolute/path/to/file/on/disk/kanboard/libs/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\StatementHandler->handleSqlError(Object(PDOException)) #1 /absolute/path/to/file/on/disk/kanboard/libs/picodb/lib/PicoDb/Database.php(257): PicoDb\StatementHandler->execute() #2 /absolute/path/to/file/on/disk/kanboard/libs/picodb/lib/PicoDb/Table.php(218): PicoDb\Database->execute('UPDATE "session...', Array) #3 /absolute/path/to/file/on/disk/kanboard/app/Core/Session/SessionHandler.php(68): PicoDb\Table->update(Array) #4 [internal function]: Kanboard\Core\Session\SessionHandler->write('3c247a28c78c66c...', 'user|a:23:{s:2:...') #5 [internal function]: session_write_close() #6 {main} thrown in /absolute/path/to/file/on/disk/kanboard/libs/picodb/lib/PicoDb/StatementHandler.php on line 351`

### Expected behaviour

Tell user there is an error without giving out so much information.

### Steps to reproduce

I am running http+php server on a home router with USB storage, it is a little slow. I think that is the reason why I often see this error information.

### Screenshots
![sIMcCpB6Pc](https://user-images.githubusercontent.com/11520416/176563444-e8db83ac-78f7-42a4-bac0-065abdb4b245.png)

### Configuration

- Kanboard version: 1.2.22
- Database type and version: sqlite 3.33.0
- PHP version: 7.4.26
- OS:  Linux 3.4.113
- Browser: Firefox/101.0

**Comment by sulisu** [comment]
Thanks a lot.

I am now running kanboard official docker image  on a faster device, and have not see error for a while.

I added `display_errors = Off` to php.ini in the container.
