### ISSUE TITLE
Apache logs are flooded by 500 errors an stack traces seemingly from Ajax requests

### ISSUE THREAD

**Issue by phep** [kanboard/kanboard#5129]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
- [x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

I installed Kanboard on my laptop and started giving it a try, with no special problems and was rather happy with it (cheers !). Then I noticed my Apache logs were at times flooded by repeated errors like:

```
127.0.0.1 - - [22/Jan/2023:08:18:28 +0100] "GET /kanboard/?controller=UserAjaxController&action=status HTTP/1.1" 500
```

with associated PHP errors like (slightly reformatted for ease of reading) :

```
[Sun Jan 22 08:18:28.234159 2023] [php:error] [pid 2324408] [client 127.0.0.1:54642] PHP Fatal error: 
Uncaught PicoDb\\SQLException: SQL Error[HY000]: SQLSTATE[HY000]:
General error: 5 database is locked in /home/me/usr/share/kanboard/libs/picodb/lib/PicoDb/StatementHandler.php:353\nStack trace:
#0/home/me/usr/share/kanboard/libs/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\\StatementHandler->handleSqlError()
#1 /home/me/usr/share/kanboard/libs/picodb/lib/PicoDb/Database.php(257): PicoDb\\StatementHandler->execute()
#2 /home/me/usr/share/kanboard/libs/picodb/lib/PicoDb/Table.php(226): PicoDb\\Database->execute()
#3 /home/me/usr/share/kanboard/app/Core/Session/SessionHandler.php(66): PicoDb\\Table->update()
#4 [internal function]: Kanboard\\Core\\Session\\SessionHandler->write()
#5 [internal function]: session_write_close()
#6 {main}
thrown in /home/me/usr/share/kanboard/libs/picodb/lib/PicoDb/StatementHandler.php on line 353
```

Looking for more details in the logs I noticed that the 500 errors where preceded by bursts of Ajax requests like:

```
127.0.0.1 - - [22/Jan/2023:08:18:27 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224733 HTTP/1.1" 304 538 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:26 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224720 HTTP/1.1" 304 538 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:26 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224721 HTTP/1.1" 304 538 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:25 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224656 HTTP/1.1" 304 539 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:26 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224723 HTTP/1.1" 304 538 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:27 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224724 HTTP/1.1" 304 538 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:28 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224734 HTTP/1.1" 304 538 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:28 +0100] "GET /kanboard/?controller=BoardAjaxController&action=check&project_id=1&timestamp=1674341221&csrf_token=951ef87ca433cb5e00773f212778f43d959fdb80ce966785260e931a91d6ad48&_=1674341224737 HTTP/1.1" 304 538 "-" "phep00"
127.0.0.1 - - [22/Jan/2023:08:18:28 +0100] "GET /kanboard/?controller=UserAjaxController&action=status HTTP/1.1" 500 560 "-" "phep00"
```

Please note the (milliseconds) timestamps of the 304's : ajax requests are sent really fast!

### Expected behaviour

No errors in logs in normal operation.

### Steps to reproduce

Unfortunately I still did not find which TTW action triggers such a behaviour that is not constant. I'll follow up on this issue if I caught something.

### Screenshots

N/A

### Logs

See above in description.

### Configuration

- Kanboard version: 1.2.26
- Database type and version:  sqlite 3.40.1 (Debian package)
- PHP version: 8.2.1 (Debian package)
- OS: Debian testing
- Browser: Firefox 102.6.0esr (Debian package)

**Comment by phep** [comment]
As I tried to catch which event could trigger this, I had 2 `tail -f` running on Apache access and error logs and I was playing with different elements in the interface, to no avail. So I left for a moment for a break, letting the board displayed. When I went back to my computer I found that the problem had reoccurred, while no human (or cats, dogs, whatever..) had used the computer. This is the URL through which the board had been called from :
```
http://localhost:8079/kanboard/?controller=BoardViewController&action=show&project_id=1&search=status%3Aopen
```
The board only contains a handful of tasks, in 2 swimlanes. The first lane columns contain 5, 3, 1, 2 tasks, the second lane columns contain 2, 2, 0, 0 tasks. Nothing fancy about those tasks, I'm still discovering the tool.

Hope this helps.

**Comment by korlikiangel** [comment]
After updating to 1.2.26, php throws 500 and the site on the server does not start, locally the site starts.
The server is hosted on amazon cloud

![image](https://user-images.githubusercontent.com/68482509/214625242-cce0350f-881e-41e2-a0a2-38b6a686eba2.png)
