### ISSUE TITLE
Logout results in crash

### ISSUE THREAD

**Issue by gramakri** [kanboard/kanboard#5308]
### Checklist

- [X ] I verified that Kanboard is correctly installed
- [X ] I verified that the problem does not come from a plugin
- [ X] I verified that the problem is not already reported
- [ X] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour
In latest release , 1.2.31, clicking logout results in a crash. The user is also not logged out

### Expected behaviour

User is redirected to login form. Behavior is not seen in 1.2.30

### Steps to reproduce

* Install Kanboard
* Authentication is configure as LDAP (via cloudron)
* See the current backtrace on logout below
* 
### Screenshots

Just a white screen on logout:
![image](https://github.com/kanboard/kanboard/assets/82041/ca5a7368-407e-4743-94f5-08b288bb3811)

Dev console:

![image](https://github.com/kanboard/kanboard/assets/82041/3eb155e7-f14a-45e2-8b21-6df43f95293f)

### Logs

```
09:07:22 - [Tue Jul 04 03:37:22.579511 2023] [php:error] [pid 30] [client 172.18.0.1:34770] PHP Fatal error:  Uncaught TypeError: Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch(): Argument #1 ($event) must be of type object, string given, called in /app/code/app/Core/Session/SessionManager.php on line 62 and defined in /app/code/vendor/symfony/event-dispatcher/EventDispatcher.php:48\nStack trace:\n#0 /app/code/app/Core/Session/SessionManager.php(62): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#1 /app/code/app/Controller/AuthController.php(61): Kanboard\\Core\\Session\\SessionManager->close()\n#2 /app/code/app/Core/Controller/Runner.php(77): Kanboard\\Controller\\AuthController->logout()\n#3 /app/code/app/Core/Controller/Runner.php(31): Kanboard\\Core\\Controller\\Runner->executeController()\n#4 /app/code/index.php(9): Kanboard\\Core\\Controller\\Runner->execute()\n#5 {main}\n  thrown in /app/code/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48
```

### Configuration

- Kanboard version: 1.2.31
- Database type and version: MySQL 8
- PHP version: 8.1
- OS: Ubuntu (cloudron)
- Browser: Firefox

**Comment by gramakri** [comment]
I have managed to reproduce this even without LDAP. So, we can rule that part out. There are no plugins as well, this is just a fresh installation and no content. Just login with admin/admin and logout.

**Comment by rilshok** [comment]
I have the same problem. Using the latest docker container the problem is reproduced. In version v1.2.29 this problem is not observed

**Comment by zjeeraar** [comment]
I have the same issue, coming from 1.2.30, upgraded to 1.2.31.
With Firefox the following error can be seen:

Fatal error:  Uncaught TypeError: Symfony\Component\EventDispatcher\EventDispatcher::dispatch(): Argument #1 ($event) must be of type object, string given, called in /var/www/app/app/Core/Session/SessionManager.php on line 62 and defined in /var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php:48 Stack trace: #0 /var/www/app/app/Core/Session/SessionManager.php(62): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #1 /var/www/app/app/Controller/AuthController.php(61): Kanboard\Core\Session\SessionManager->close() #2 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Controller\AuthController->logout() #3 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #4 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner->execute() #5 {main}  thrown in /var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48

**Comment by danilo85-br** [comment]
> I have the same issue, coming from 1.2.30, upgraded to 1.2.31. With Firefox the following error can be seen:
> 
> `Fatal error: Uncaught TypeError: Symfony\Component\EventDispatcher\EventDispatcher::dispatch(): Argument #1 ($event) must be of type object, string given, called in /var/www/app/app/Core/Session/SessionManager.php on line 62 and defined in /var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php:48 Stack trace: #0 /var/www/app/app/Core/Session/SessionManager.php(62): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #1 /var/www/app/app/Controller/AuthController.php(61): Kanboard\Core\Session\SessionManager->close() #2 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Controller\AuthController->logout() #3 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #4 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner->execute() #5 {main} thrown in /var/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48`

I've got the same error. I've installed with only the php files on a subdirectory.

**Comment by talpa** [comment]
The same problem

**Comment by stultitiophobia** [comment]
Same here, too

But not on logon but on cronjob execution

**Comment by mandrewsan** [comment]
Same!

**Comment by ecerichter** [comment]
Same problem with logout here.

**Comment by ngosang** [comment]
Same problem

**Comment by espiney** [comment]
I have a fresh install, and I'm getting this as well.  

Do we know a work around?

**Comment by petski** [comment]
#5309

**Comment by ecerichter** [comment]
The patch works for me. Thanks!
