### ISSUE TITLE
Uncaught TypeError: Symfony\Component\EventDispatcher\EventDispatcher when running cli cronjob

### ISSUE THREAD

**Issue by stultitiophobia** [kanboard/kanboard#5313]
When running the cronjob (cli cronjob) kanboard throws an error:

PHP Fatal error:  Uncaught TypeError: Symfony\Component\EventDispatcher\EventDispatcher::dispatch(): Argument #1 ($event) must be of type object, string given, called in /var/www/vhosts/<domain>/board.<domain>/app/Console/TaskTriggerCommand.php on line 50 and defined in /var/www/vhosts/<domain>/board.<domain>/vendor/symfony/event-dispatcher/EventDispatcher.php:48
Stack trace:
#0 /var/www/vhosts/<domain>/board.<domain>/app/Console/TaskTriggerCommand.php(50): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#1 /var/www/vhosts/<domain>/board.<domain>/app/Console/TaskTriggerCommand.php(27): Kanboard\Console\TaskTriggerCommand->sendEvent()
#2 /var/www/vhosts/<domain>/board.<domain>/vendor/symfony/console/Command/Command.php(298): Kanboard\Console\TaskTriggerCommand->execute()
#3 /var/www/vhosts/<domain>/board.<domain>/app/Console/CronjobCommand.php(29): Symfony\Component\Console\Command\Command->run()
#4 /var/www/vhosts/<domain>/board.<domain>/vendor/symfony/console/Command/Command.php(298): Kanboard\Console\CronjobCommand->execute()
#5 /var/www/vhosts/<domain>/board.<domain>/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#6 /var/www/vhosts/<domain>/board.<domain>/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#7 /var/www/vhosts/<domain>/board.<domain>/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#8 /var/www/vhosts/<domain>/board.<domain>/cli(21): Symfony\Component\Console\Application->run()
#9 {main}
 thrown in /var/www/vhosts/<domain>/board.<domain>/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48

I'm running:
kanboard Version: 1.2.31
PHP Version: 8.2.7
PHP SAPI: fpm-fcgi
HTTP-Client: cURL
OS Version: Linux 5.15.0-76-generic
Datenbanktreiber: mysql
Datenbank Version: 10.6.12-MariaDB-0ubuntu0.22.04.1

I applied the patches #5309 manually bit it does not fix the error.

**Comment by richardrblocker** [comment]
A similar error is being thrown by the plugin GitlabWebhook following update to version 1.2.31, which is still broken with kanboard version 1.2.32.

```
[Wed Jul 19 10:14:39.392755 2023] [php7:error] [pid 3381335] [client 10.x.x.x:53276] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch() must be an object, string given, called in /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php on line 297 and defined in /srv/kanboard-1.2.31/vendor/symfony/event-dispatcher/EventDispatcher.php:48\nStack trace:\n#0 /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php(297): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#1 /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php(69): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->handleCommentEvent()\n#2 /srv/kanboard-1.2.31/plugins/GitlabWebhook/Controller/WebhookController.php(27): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->parsePayload()\n#3 /srv/kanboard-1.2.31/app/Core/Controller/Runner.php(77): Kanboard\\Plugin\\GitlabWebhook\\Controller\\WebhookController->handler()\n#4 /srv/kanboard-1.2.31/app/Core/Controller/Runner.php(31): Kanboard\\Core\\Controller\\Runner->executeController()\n#5 /srv/kanboard-1.2.31/index.php(9): Kanb in /srv/kanboard-1.2.31/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48

[Wed Jul 19 11:00:27.452709 2023] [php7:error] [pid 3379404] [client 10.x.x.x:37548] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch() must be an object, string given, called in /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php on line 297 and defined in /srv/kanboard-1.2.31/vendor/symfony/event-dispatcher/EventDispatcher.php:48\nStack trace:\n#0 /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php(297): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#1 /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php(69): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->handleCommentEvent()\n#2 /srv/kanboard-1.2.31/plugins/GitlabWebhook/Controller/WebhookController.php(27): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->parsePayload()\n#3 /srv/kanboard-1.2.31/app/Core/Controller/Runner.php(77): Kanboard\\Plugin\\GitlabWebhook\\Controller\\WebhookController->handler()\n#4 /srv/kanboard-1.2.31/app/Core/Controller/Runner.php(31): Kanboard\\Core\\Controller\\Runner->executeController()\n#5 /srv/kanboard-1.2.31/index.php(9): Kanb in /srv/kanboard-1.2.31/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48

[Wed Jul 19 11:12:36.331138 2023] [php7:error] [pid 3381359] [client 10.x.x.x:46958] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch() must be an object, string given, called in /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php on line 197 and defined in /srv/kanboard-1.2.31/vendor/symfony/event-dispatcher/EventDispatcher.php:48\nStack trace:\n#0 /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php(197): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#1 /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php(165): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->handleIssueOpened()\n#2 /srv/kanboard-1.2.31/plugins/GitlabWebhook/WebhookHandler.php(67): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->handleIssueEvent()\n#3 /srv/kanboard-1.2.31/plugins/GitlabWebhook/Controller/WebhookController.php(27): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->parsePayload()\n#4 /srv/kanboard-1.2.31/app/Core/Controller/Runner.php(77): Kanboard\\Plugin\\GitlabWebhook\\Controller\\WebhookController->handler()\n#5 /srv/kanboard-1.2 in /srv/kanboard-1.2.31/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48

[Wed Jul 19 11:25:07.470165 2023] [php7:error] [pid 3430078] [client 10.x.x.x:52764] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch() must be an object, string given, called in /srv/kanboard-1.2.32/plugins/GitlabWebhook/WebhookHandler.php on line 297 and defined in /srv/kanboard-1.2.32/vendor/symfony/event-dispatcher/EventDispatcher.php:48\nStack trace:\n#0 /srv/kanboard-1.2.32/plugins/GitlabWebhook/WebhookHandler.php(297): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#1 /srv/kanboard-1.2.32/plugins/GitlabWebhook/WebhookHandler.php(69): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->handleCommentEvent()\n#2 /srv/kanboard-1.2.32/plugins/GitlabWebhook/Controller/WebhookController.php(27): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->parsePayload()\n#3 /srv/kanboard-1.2.32/app/Core/Controller/Runner.php(77): Kanboard\\Plugin\\GitlabWebhook\\Controller\\WebhookController->handler()\n#4 /srv/kanboard-1.2.32/app/Core/Controller/Runner.php(31): Kanboard\\Core\\Controller\\Runner->executeController()\n#5 /srv/kanboard-1.2.32/index.php(9): Kanb in /srv/kanboard-1.2.32/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48

[Wed Jul 19 11:25:27.914720 2023] [php7:error] [pid 3430069] [client 10.x.x.x:49386] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\\Component\\EventDispatcher\\EventDispatcher::dispatch() must be an object, string given, called in /srv/kanboard-1.2.32/plugins/GitlabWebhook/WebhookHandler.php on line 253 and defined in /srv/kanboard-1.2.32/vendor/symfony/event-dispatcher/EventDispatcher.php:48\nStack trace:\n#0 /srv/kanboard-1.2.32/plugins/GitlabWebhook/WebhookHandler.php(253): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()\n#1 /srv/kanboard-1.2.32/plugins/GitlabWebhook/WebhookHandler.php(167): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->handleIssueClosed()\n#2 /srv/kanboard-1.2.32/plugins/GitlabWebhook/WebhookHandler.php(67): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->handleIssueEvent()\n#3 /srv/kanboard-1.2.32/plugins/GitlabWebhook/Controller/WebhookController.php(27): Kanboard\\Plugin\\GitlabWebhook\\WebhookHandler->parsePayload()\n#4 /srv/kanboard-1.2.32/app/Core/Controller/Runner.php(77): Kanboard\\Plugin\\GitlabWebhook\\Controller\\WebhookController->handler()\n#5 /srv/kanboard-1.2 in /srv/kanboard-1.2.32/vendor/symfony/event-dispatcher/EventDispatcher.php on line 48

```

**Comment by richardrblocker** [comment]
This may not be the best place to post this, but if anyone is interested in a fix for the GitlabWebhook plugin, changing `WebhookHandler.php` as shown below seems to do it:

```
diff --git a/WebhookHandler.php b/WebhookHandler.php
index 1b61222..5807b47 100644
--- a/WebhookHandler.php
+++ b/WebhookHandler.php
@@ -193,8 +193,8 @@ class WebhookHandler extends Base
         );
 
         $this->dispatcher->dispatch(
-            self::EVENT_ISSUE_OPENED,
-            new GenericEvent($event)
+            new GenericEvent($event),
+            self::EVENT_ISSUE_OPENED
         );
 
         return true;
@@ -219,8 +219,8 @@ class WebhookHandler extends Base
             );
 
             $this->dispatcher->dispatch(
-                self::EVENT_ISSUE_REOPENED,
-                new GenericEvent($event)
+                new GenericEvent($event),
+                self::EVENT_ISSUE_REOPENED
             );
 
             return true;
@@ -249,8 +249,8 @@ class WebhookHandler extends Base
             );
 
             $this->dispatcher->dispatch(
-                self::EVENT_ISSUE_CLOSED,
-                new GenericEvent($event)
+                new GenericEvent($event),
+                self::EVENT_ISSUE_CLOSED
             );
 
             return true;
@@ -293,8 +293,8 @@ class WebhookHandler extends Base
             );
 
             $this->dispatcher->dispatch(
-                self::EVENT_ISSUE_COMMENT,
-                new GenericEvent($event)
+                new GenericEvent($event),
+                self::EVENT_ISSUE_COMMENT
             );
 
             return true;


```

Basically just switching the order of the two items in each `$this->dispatcher->dispatch(` call. 
Credit belongs to https://stackoverflow.com/questions/57540654/symfony-4-custom-event-dispatcher-not-working
